# Generated by Django 2.1.7 on 2019-03-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo',
            name='imagem',
            field=models.ImageField(default='img/cart.jpg', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
