# Generated by Django 2.1.7 on 2019-03-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesta', '0002_auto_20190327_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='imagem',
            field=models.ImageField(default='static/img/cart.jpg', upload_to='static/img/'),
        ),
    ]
